---
- name: Test playbook to install http
  hosts: all
  gather_facts: false
  vars:
    packages:
      - httpd
      - firewalld
  tasks:
    - name: Installing packages
      yum:
        name: '{{ packages }}'
        state: latest

    - name: Enable/Start Services
      service:
        name: '{{ item }}'
        enabled: true
        state: started
      loop: '{{ packages }}'
